@startuml
title Классификация компьютерных моделей

package "Компьютерные модели" {
    
    node "По способу представления" {
        [Имитационные]
        [Аналитические\n(математические)]
    }

    node "По учёту времени" {
        [Статические]
        node "Динамические" {
            [Дискретные]
            [Непрерывные]
        }
    }

    node "По степени определённости" {
        [Детерминированные]
        [Стохастические]
    }

    node "По структуре" {
        [Монолитные]
        [Модульные\n(иерархические)]
    }

    node "По характеру\nмоделируемой стороны объекта" {
        [Функциональные\n(поведенческие)]
        [Структурные]
        [Информационные]
    }
}
@enduml
